version: "3.8"

services:
  node:
    container_name: node_server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/app
    command: yarn dev
    networks: 
      - common
    environment:
      PORT: 3000

  mongo: 
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    networks: 
      - common
    
networks:
  common: 
