version: "3.8"

services:
  node:
    container_name: node_server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/app
    command: yarn dev
    networks: 
      - common
    environment:
      APP_PORT: 3000
      MONGO_URL: 'mongodb+srv://quitq-dev:Quangqui12345@mern-learnit.n1i7rnl.mongodb.net/?retryWrites=true&w=majority'

  mongo: 
    container_name: mongo
    image: mongo
    ports:
      - 3006:3006
    volumes:
      - ./data:/data/db
    networks: 
      - common
    
networks:
  common: 
